/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Time,
  'isActive' : IDL.Bool,
  'summary' : IDL.Text,
  'image' : ExternalBlob,
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'image' : ExternalBlob,
});
export const TravelPackage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'destinationId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'details' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'displayOrder' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'submissionTime' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const TermsAndConditions = IDL.Record({
  'gst' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'pricing' : IDL.Text,
  'advancePayment' : IDL.Text,
  'rateChanges' : IDL.Text,
});
export const FeaturedCategory = IDL.Variant({
  'domestic' : IDL.Null,
  'international' : IDL.Null,
});
export const FeaturedDestination = IDL.Record({
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : FeaturedCategory,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'user' : IDL.Principal,
  'passengerName' : IDL.Text,
  'bookingDate' : Time,
  'flightId' : IDL.Nat,
  'packageId' : IDL.Opt(IDL.Nat),
});
export const Flight = IDL.Record({
  'id' : IDL.Nat,
  'arrival' : IDL.Text,
  'date' : Time,
  'isActive' : IDL.Bool,
  'availableSeats' : IDL.Nat,
  'airline' : IDL.Text,
  'price' : IDL.Nat,
  'departure' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'addDestination' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addFlight' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'addTravelPackage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getActiveBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getActiveDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getActivePackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
  'getActiveTestimonials' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedDestinations' : IDL.Func(
      [],
      [
        IDL.Record({
          'terms' : TermsAndConditions,
          'domestic' : IDL.Vec(FeaturedDestination),
          'international' : IDL.Vec(FeaturedDestination),
        }),
      ],
      ['query'],
    ),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFlights' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Flight)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'toggleBlogPost' : IDL.Func([IDL.Nat], [], []),
  'toggleDestination' : IDL.Func([IDL.Nat], [], []),
  'toggleFlight' : IDL.Func([IDL.Nat], [], []),
  'toggleTestimonial' : IDL.Func([IDL.Nat], [], []),
  'toggleTravelPackage' : IDL.Func([IDL.Nat], [], []),
  'updateBlogPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateDestination' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateFlight' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateTravelPackage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Time,
    'isActive' : IDL.Bool,
    'summary' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'image' : ExternalBlob,
  });
  const TravelPackage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'destinationId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'details' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'displayOrder' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'submissionTime' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TermsAndConditions = IDL.Record({
    'gst' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'pricing' : IDL.Text,
    'advancePayment' : IDL.Text,
    'rateChanges' : IDL.Text,
  });
  const FeaturedCategory = IDL.Variant({
    'domestic' : IDL.Null,
    'international' : IDL.Null,
  });
  const FeaturedDestination = IDL.Record({
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : FeaturedCategory,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'user' : IDL.Principal,
    'passengerName' : IDL.Text,
    'bookingDate' : Time,
    'flightId' : IDL.Nat,
    'packageId' : IDL.Opt(IDL.Nat),
  });
  const Flight = IDL.Record({
    'id' : IDL.Nat,
    'arrival' : IDL.Text,
    'date' : Time,
    'isActive' : IDL.Bool,
    'availableSeats' : IDL.Nat,
    'airline' : IDL.Text,
    'price' : IDL.Nat,
    'departure' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'addDestination' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'addFlight' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'addTravelPackage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getActiveBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getActiveDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getActivePackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
    'getActiveTestimonials' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedDestinations' : IDL.Func(
        [],
        [
          IDL.Record({
            'terms' : TermsAndConditions,
            'domestic' : IDL.Vec(FeaturedDestination),
            'international' : IDL.Vec(FeaturedDestination),
          }),
        ],
        ['query'],
      ),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFlights' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Flight)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'toggleBlogPost' : IDL.Func([IDL.Nat], [], []),
    'toggleDestination' : IDL.Func([IDL.Nat], [], []),
    'toggleFlight' : IDL.Func([IDL.Nat], [], []),
    'toggleTestimonial' : IDL.Func([IDL.Nat], [], []),
    'toggleTravelPackage' : IDL.Func([IDL.Nat], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateDestination' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateFlight' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateTravelPackage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };