/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : Time,
  'isActive' : boolean,
  'summary' : string,
  'image' : ExternalBlob,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'user' : Principal,
  'passengerName' : string,
  'bookingDate' : Time,
  'flightId' : bigint,
  'packageId' : [] | [bigint],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'submissionTime' : Time,
}
export interface Destination {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export type FeaturedCategory = { 'domestic' : null } |
  { 'international' : null };
export interface FeaturedDestination {
  'duration' : string,
  'name' : string,
  'description' : string,
  'category' : FeaturedCategory,
}
export interface Flight {
  'id' : bigint,
  'arrival' : string,
  'date' : Time,
  'isActive' : boolean,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : bigint,
  'departure' : string,
}
export interface TermsAndConditions {
  'gst' : string,
  'cancellationPolicy' : string,
  'pricing' : string,
  'advancePayment' : string,
  'rateChanges' : string,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'displayOrder' : [] | [bigint],
  'name' : string,
  'isActive' : boolean,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface TravelPackage {
  'id' : bigint,
  'title' : string,
  'destinationId' : bigint,
  'isActive' : boolean,
  'details' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'addDestination' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'addFlight' : ActorMethod<
    [string, string, string, Time, bigint, bigint],
    undefined
  >,
  'addTestimonial' : ActorMethod<
    [string, [] | [ExternalBlob], bigint, string, [] | [bigint]],
    undefined
  >,
  'addTravelPackage' : ActorMethod<
    [bigint, string, string, bigint, ExternalBlob],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[bigint, [] | [bigint], string], bigint>,
  'getActiveBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getActiveDestinations' : ActorMethod<[], Array<Destination>>,
  'getActivePackages' : ActorMethod<[], Array<TravelPackage>>,
  'getActiveTestimonials' : ActorMethod<[bigint], Array<Testimonial>>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedDestinations' : ActorMethod<
    [],
    {
      'terms' : TermsAndConditions,
      'domestic' : Array<FeaturedDestination>,
      'international' : Array<FeaturedDestination>,
    }
  >,
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFlights' : ActorMethod<[string, string], Array<Flight>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'toggleBlogPost' : ActorMethod<[bigint], undefined>,
  'toggleDestination' : ActorMethod<[bigint], undefined>,
  'toggleFlight' : ActorMethod<[bigint], undefined>,
  'toggleTestimonial' : ActorMethod<[bigint], undefined>,
  'toggleTravelPackage' : ActorMethod<[bigint], undefined>,
  'updateBlogPost' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateDestination' : ActorMethod<[bigint, string, string], undefined>,
  'updateFlight' : ActorMethod<
    [bigint, string, string, string, Time, bigint, bigint],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, bigint, string, [] | [bigint]],
    undefined
  >,
  'updateTravelPackage' : ActorMethod<
    [bigint, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];